'use client'

import { Search, Sparkles, CheckCircle2 } from 'lucide-react'

export default function AutoFixCapabilities() {
  const detectableIssues = [
    'Document metadata (title, language)',
    'Image alt text',
    'Heading structure (H1-H6)',
    'Language span tagging',
    'Form field labels',
    'Link text improvements',
    'Color contrast (WCAG AA)',
    'Color as only indicator (text alternatives)',
    'Text resizing (minimum font sizes)',
    'Images of text (OCR extraction)',
    'Table structure (structure tree)',
    'List structure (structure tree)',
    'Reading order',
    'Keyboard traps',
    'Time limits',
    'Script accessibility',
    'Plug-in alternatives',
    'Audio descriptions'
  ]

  return (
    <div className="card">
      <h2 className="text-lg font-medium text-gray-900 mb-3">Issue Detection</h2>
      <div className="mb-4">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-2xl font-bold text-blue-600">{detectableIssues.length}</span>
          <span className="text-sm text-gray-600">issue types detected</span>
        </div>
        <p className="text-xs text-gray-600 mb-3">
          Our AI-powered scanner detects these accessibility issues and provides detailed step-by-step suggestions for fixing them.
        </p>
      </div>

      <div className="space-y-4">
        {/* Detectable Issues */}
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Search className="h-4 w-4 text-blue-600" />
            <h3 className="text-sm font-semibold text-gray-900">Issues We Detect</h3>
          </div>
          <div className="space-y-1.5 max-h-64 overflow-y-auto">
            {detectableIssues.map((item, index) => (
              <div key={index} className="flex items-start gap-2">
                <div className="w-1.5 h-1.5 bg-blue-500 rounded-full mt-1.5 flex-shrink-0" />
                <p className="text-xs text-gray-700">{item}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="mt-4 pt-4 border-t border-gray-200">
        <div className="flex items-start gap-2">
          <Sparkles className="h-4 w-4 text-blue-600 mt-0.5 flex-shrink-0" />
          <div>
            <p className="text-xs font-medium text-gray-900 mb-1">AI-Powered Suggestions</p>
            <p className="text-xs text-gray-600">
              Each detected issue includes detailed, step-by-step remediation instructions generated by AI to help you fix accessibility problems efficiently.
            </p>
          </div>
        </div>
      </div>

      <div className="mt-3 pt-3 border-t border-gray-200">
        <div className="flex items-start gap-2">
          <CheckCircle2 className="h-4 w-4 text-green-600 mt-0.5 flex-shrink-0" />
          <div>
            <p className="text-xs font-medium text-gray-900 mb-1">Auto-Added to Backlog</p>
            <p className="text-xs text-gray-600">
              All detected issues are automatically added to your product backlog for tracking and prioritization.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
